# Site settings
title: "Kirill Babich"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Kirill Babich"
resume_title:                   "Senior Full-Stack Engineer & Engineering Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kilimondgaro@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "Barcelona, Spain"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a Software Engineer with a deep passion for building well-crafted, meaningful software that positively impacts people’s lives. While I have extensive experience in mobile development (React Native), my expertise spans the entire stack, including frontend and backend development.<br/><br/>I thrive on taking responsibility—whether it’s leading teams, driving technical decisions, or ensuring software quality. For me, engineering is more than just writing code; it’s about craftsmanship, mastery, and continuous learning.<br/><br/>Above all, I am driven by purpose and human connection. I believe that the most valuable software isn’t just functional—it solves real problems, brings people together, and enhances lives. Whether collaborating with teams or building impactful products, my goal is always to create technology that truly matters.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kilimondjaro/"
#  resume_twitter_url:           "https://twitter.com/kilimondjaro_"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kirill-babich-63961b12a/"
  # resume_instagram_url:         "insert your Instagram URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
